---
- name: detect if rubies are installed
  command: '{{ rvm1 }} {{ item }} do true'
  changed_when: false
  failed_when: false
  register: detect_rubies
  with_items: rvm1_rubies
  when: rvm1_rubies

- name: ensure rubies are installed
  sudo: yes
  command: '{{ rvm1 }} install {{ item.item }}'
  when: rvm1_rubies and item.rc != 0
  with_items: detect_rubies.results

- name: detect default ruby version
  command: '{{ rvm1 }} alias list default'
  changed_when: false
  register: detect_default_ruby_version

- name: ensure default ruby is selected
  sudo: yes
  command: '{{ rvm1 }} alias create default {{ rvm1_default_ruby_version }}'
  when: detect_default_ruby_version.stdout == '' or rvm1_default_ruby_version not in detect_default_ruby_version.stdout

- name: ensure default ruby is being used
  sudo: yes
  command: '{{ rvm1 }} use {{ rvm1_default_ruby_version }}'
  when: detect_default_ruby_version.stdout == '' or rvm1_default_ruby_version not in detect_default_ruby_version.stdout

- name: ensure rvm install path is writable by the set owner:group
  sudo: yes
  file: path='{{ rvm1_install_path }}' state=directory recurse=yes owner='{{ rvm1_user }}' group='{{ rvm1_group }}'

- name: detect if ruby version can be deleted
  command: '{{ rvm1 }} {{ rvm1_delete_ruby }} do true'
  changed_when: false
  failed_when: false
  register: detect_delete_ruby
  when: rvm1_delete_ruby

- name: ensure ruby version is deleted
  command: '{{ rvm1 }} remove {{ rvm1_delete_ruby }}'
  changed_when: false
  when: rvm1_delete_ruby and detect_delete_ruby.rc == 0
